# Generated by Django 2.1.5 on 2019-02-04 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('src_lang', models.CharField(blank=True, choices=[('txt', 'text')], default='txt', max_length=100)),
                ('src_code', models.CharField(max_length=50000)),
                ('pwd', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
