# Generated by Django 2.1.5 on 2019-02-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='src_lang',
            field=models.CharField(blank=True, choices=[('text', 'Plain Text'), ('c_cpp', 'C++'), ('java', 'Java')], default='txt', max_length=100),
        ),
    ]
